allowBuilds:
  esbuild: true
  sharp: true

overrides:
  "cookie": "1.1.1"
  "vite@^7.3.2": "7.3.5"
  "undici": "^7.29.0"
  "brace-expansion": "1.1.15"
  "js-yaml": "4.3.2"
  "smol-toml": "^1.7.1"
  "devalue": "^5.9.1"
  "esbuild": "^0.28.1"
  "@babel/core": "^7.29.1"
