allowBuilds:
  esbuild: true
  sharp: true

overrides:
  "vite@^7.3.2": "7.3.5"
  "undici": "^7.28.0"
  "brace-expansion": "1.1.15"
  "js-yaml": "4.2.0"
  "esbuild": "^0.28.1"
  "@babel/core": "^7.29.1"
