/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "surface-bright": "#fcf9f8",
        "primary-fixed-dim": "#edc06d",
        "secondary-fixed": "#ffddb8",
        "on-primary": "#ffffff",
        "inverse-on-surface": "#f3f0ef",
        "outline": "#807666",
        "on-secondary-container": "#78572e",
        "on-surface-variant": "#4e4638",
        "on-error": "#ffffff",
        "error-container": "#ffdad6",
        "primary-container": "#c2994a",
        "background": "#fcf9f8",
        "surface-container-highest": "#e5e2e1",
        "tertiary": "#5f5e5e",
        "surface": "#fcf9f8",
        "surface-container": "#f0edec",
        "primary-fixed": "#ffdea6",
        "on-tertiary-container": "#363636",
        "on-background": "#1c1b1b",
        "inverse-surface": "#313030",
        "tertiary-container": "#a09f9f",
        "surface-variant": "#e5e2e1",
        "on-secondary": "#ffffff",
        "surface-tint": "#7a590c",
        "on-error-container": "#93000a",
        "on-secondary-fixed-variant": "#5f411a",
        "secondary-container": "#fdcf9c",
        "error": "#ba1a1a",
        "surface-container-lowest": "#ffffff",
        "tertiary-fixed-dim": "#c8c6c6",
        "surface-dim": "#dcd9d9",
        "on-primary-fixed": "#271900",
        "on-tertiary-fixed-variant": "#474747",
        "on-tertiary": "#ffffff",
        "on-primary-fixed-variant": "#5e4200",
        "surface-container-low": "#f6f3f2",
        "primary": "#7a590c",
        "on-primary-container": "#493200",
        "outline-variant": "#d2c5b3",
        "secondary": "#79582f",
        "on-secondary-fixed": "#2b1700",
        "surface-container-high": "#ebe7e7",
        "on-tertiary-fixed": "#1b1c1c",
        "tertiary-fixed": "#e4e2e1",
        "inverse-primary": "#edc06d",
        "secondary-fixed-dim": "#ebbf8d",
        "on-surface": "#1c1b1b"
      },
      fontFamily: {
        "headline": ["Work Sans", "sans-serif"],
        "body": ["Inter", "sans-serif"],
        "label": ["Inter", "sans-serif"]
      },
      borderRadius: {
        "DEFAULT": "0.125rem",
        "lg": "0.25rem",
        "xl": "0.5rem",
        "full": "0.75rem"
      },
    },
  },
  plugins: [],
}
